version: "3.8"
services:
  postgres-seternak:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    #   Set a volume for data and initial sql script
    #   May configure initial db for future demo
    volumes:
      - "pgdata_seternak:/var/lib/postgresql/data"
      # - ./init:/docker-entrypoint-initdb.d/
    command: [ "postgres", "-c", "log_statement=all" ]

  redis-seternak:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "redisdata_seternak:/data"

  seternak-backend:
    build:
      context: ./
      target: builder
    image: seternak-backend
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./:/go/src/app
    depends_on:
      - postgres-seternak
    # have to use $$ (double-dollar) so docker doesn't try to substitute a variable
    command: reflex -v -r "\.go$$" -s -- sh -c "go run ./"

volumes:
  pgdata_seternak:
  redisdata_seternak: